FROM python:3.11

WORKDIR /cellpack
COPY . /cellpack

RUN python -m pip install --upgrade pip --root-user-action=ignore
RUN python -m pip install .
RUN python -m pip install aiohttp mdutils

EXPOSE 80

RUN apt-get update && apt-get install -y awscli

COPY docker/entrypoint-ecs.sh /usr/local/bin/
RUN ["chmod", "+x", "/usr/local/bin/entrypoint-ecs.sh"]
ENTRYPOINT ["/usr/local/bin/entrypoint-ecs.sh"]
