name: UV & Dependencies
description: Install UV and dependencies
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install dependencies
      shell: bash
      run: |
          uv sync --dev