name: Documentation

on:
  push:
    branches:
      - main
      - fix/documentation-workflow
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/dependencies

    - name: Generate Docs
      run: |
        pdm run make gen-docs
        touch docs/_build/html/.nojekyll
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/
  
  deploy:
    needs: docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

