name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    if: ${{ !contains(github.event.head_commit.message, 'Bump version') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: "pip"
        cache-dependency-path: setup.py
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Generate Docs
      run: |
        make gen-docs
        touch docs/_build/html/.nojekyll
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html/ # The folder the action should deploy.

