name: Cleanup Firebase Metadata

on:
    schedule:
        - cron: "24 18 * * 1" # Runs at 18:24 UTC every Monday

jobs:
    cleanup:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.9]
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/dependencies
            -   name: Cleanup Firebase Metadata
                env:
                    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                    FIREBASE_EMAIL: ${{ secrets.FIREBASE_EMAIL }}
                run: |
                    pdm run python cellpack/bin/cleanup_tasks.py
