name: Cleanup Firebase Metadata

on:
    push:
        branches:
            - feature/firebase-delete-metadata
    schedule:
        - cron: "24 18 * * 1" # Runs at 18:24 UTC every Monday

jobs:
    cleanup:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.9]
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install .[all]
            -   name: Cleanup Firebase Metadata
                env:
                    STAGING_FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
                    STAGING_FIREBASE_EMAIL: ${{ secrets.STAGING_FIREBASE_EMAIL }}
                run: |
                    python cellpack/bin/cleanup_tasks.py
                    echo "Cleanup complete."
